### ISSUE TITLE
Question regarding performance

### ISSUE THREAD

**Issue by debopamsengupta** [Schoonology/weighted#1]
Hi @Schoonology 
The README says
![image](https://cloud.githubusercontent.com/assets/9649659/13566587/352eb958-e491-11e5-9f43-cd2670f812c4.png)

Does this mean, performance goes down if the weights are constantly changing ? 
Thanks

**Comment by Schoonology** [comment]
Yes, though the performance degrades a constant amount: continuing to change the weights won't continue to make the problem worse.

That said, the reverse is true: if at some point the weights settle (even if only for a period), the optimization will kick in and performance should increase again.

Both of these statements are moot if you use the `normal` flag, and normalize all weights to 1 manually.

**Comment by debopamsengupta** [comment]
Thanks a lot :)
